# Generated by Django 2.2 on 2020-06-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerPod_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerPod_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerPod_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerPod_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServerPod_5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Megapod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Megapod_description', models.CharField(max_length=100)),
                ('ServerPod_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Api.ServerPod_1')),
                ('ServerPod_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Api.ServerPod_2')),
                ('ServerPod_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Api.ServerPod_3')),
                ('ServerPod_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Api.ServerPod_4')),
                ('ServerPod_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Api.ServerPod_5')),
            ],
            options={
                'verbose_name_plural': 'Megapod',
            },
        ),
    ]
